# Generated by Django 2.1.7 on 2019-05-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
